config/routes.rb
TutorNetwork::Application.routes.draw do
  get "customer_homes/index_tutor_post/:page" => "customer_homes#index_tutor_post"
  get "customer_homes/index_recipe/:page" => "customer_homes#index_recipe"
  get "customer_homes/show_tutor_post/:tutor_post_id" => "customer_homes#show_tutor_post"
  post "customer_homes/create_recipe/:tutor_id/:tutor_post_id" => "customer_homes#create_recipe"
  get "customer_homes/show_recipe/:recipe_id" => "customer_homes#show_recipe"
  get "customer_homes/delete_recipe/:recipe_id" => "customer_homes#delete_recipe"
  post "customer_homes/rate/:tutor_id" => "customer_homes#rate"

  get "customer_posts/index_customer_post/:page" => "customer_posts#index_customer_post"
  get "customer_posts/new_customer_post" => "customer_posts#new_customer_post"
  get "customer_posts/edit_customer_post/:customer_post_id" => "customer_posts#edit_customer_post"
  post "customer_posts/create_customer_post/" => "customer_posts#create_customer_post"
  post "customer_posts/delete_customer_post/:customer_post_id" => "customer_posts#delete_customer_post"
  post "customer_posts/update_customer_post/:customer_post_id" => "customer_posts#update_customer_post"
  get "customer_posts/index_recipe/:page" => "customer_posts#index_recipe"
  get "customer_posts/show_customer_post/:customer_post_id" => "customer_posts#show_customer_post"
  get "customer_posts/show_recipe/:recipe_id" => "customer_posts#show_recipe"
  get "customer_posts/accept_recipe/:recipe_id" => "customer_posts#accept_recipe"
  get "customer_posts/deny_recipe/:recipe_id" => "customer_posts#deny_recipe"

  get "tutor_homes/index_customer_post/:page" => "tutor_homes#index_customer_post"
  get "tutor_homes/index_recipe/:page" => "tutor_homes#index_recipe"
  get "tutor_homes/show_customer_post/:customer_post_id" => "tutor_homes#show_customer_post"
  post "tutor_homes/create_recipe/:customer_id/:customer_post_id" => "tutor_homes#create_recipe"
  get "tutor_homes/show_recipe/:recipe_id" => "tutor_homes#show_recipe"
  get "tutor_homes/delete_recipe/:recipe_id" => "tutor_homes#delete_recipe"

  get "tutor_posts/index_tutor_post/:page" => "tutor_posts#index_tutor_post"
  get "tutor_posts/new_tutor_post" => "tutor_posts#new_tutor_post"
  get "tutor_posts/edit_tutor_post/:tutor_post_id" => "tutor_posts#edit_tutor_post"
  post "tutor_posts/create_tutor_post/" => "tutor_posts#create_tutor_post"
  post "tutor_posts/delete_tutor_post/:tutor_post_id" => "tutor_posts#delete_tutor_post"
  post "tutor_posts/update_tutor_post/:tutor_post_id" => "tutor_posts#update_tutor_post"
  get "tutor_posts/index_recipe/:page" => "tutor_posts#index_recipe"
  get "tutor_posts/show_tutor_post/:tutor_post_id" => "tutor_posts#show_tutor_post"
  get "tutor_posts/show_recipe/:recipe_id" => "tutor_posts#show_recipe"
  get "tutor_posts/accept_recipe/:recipe_id" => "tutor_posts#accept_recipe"
  get "tutor_posts/deny_recipe/:recipe_id" => "tutor_posts#deny_recipe"

  get "mods/index_customer_post/:page" => "mods#index_customer_post"
  get "mods/show_customer_post/:customer_post_id" => "mods#show_customer_post"
  get "mods/index_tutor_post/:page" => "mods#index_tutor_post"
  get "mods/show_tutor_post/:tutor_post_id" => "mods#show_tutor_post"
  get "mods/publish_customer_post/:post_id" => "mods#publish_customer_post"
  get "mods/refuse_customer_post/:post_id" => "mods#refuse_customer_post"
  get "mods/publish_tutor_post/:post_id" => "mods#publish_tutor_post"
  get "mods/refuse_tutor_post/:post_id" => "mods#refuse_tutor_post"


  get "users/index/:page" => "users#index"
  get "users/show/:user_id" => "users#show"
  get "users/new" => "users#new"
  post "users/create" => "users#create"
  post "users/update/:user_id" => "users#update"
  get "users/edit/:user_id" => "users#edit"
  post "users/delete/:user_id" => "users#delete"
  get "users/self_edit" => "users#self_edit"
  post "users/self_update" => "users#self_update"

  get "/faq" => "etcs#faq"
  get "/contact" => "etcs#contact"

  get "/searches/customer" => "searches#customer"
  post "/searches/customer" => "searches#customer_post"
  get "/searches/customer_tutor" => "searches#customer_tutor"
  post "/searches/customer_tutor" => "searches#customer_tutor_post"

  get "/searches/tutor" => "searches#tutor"
  post "/searches/tutor" => "searches#tutor_post"
  get "/searches/tutor_customer" => "searches#tutor_customer"
  post "/searches/tutor_customer" => "searches#tutor_customer_post"

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  devise_for :users do
    get "/", :to => "devise/sessions#new"
  end

  root :to => "devise/sessions#new"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  ajaxful_rater
  ajaxful_rateable :allow_update => true

  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :gender, :address, :ward, :district, :city_province, :role, :confirmed_at

  self.per_page = 12

  validates_presence_of :username, :address, :ward, :district, :city_province, :role
  validates_uniqueness_of :username
  
  has_one :rate
  belongs_to :rate
  has_one :user, :through => :rate
  has_many :tutor_posts, :dependent => :destroy
  has_many :customer_posts, :dependent => :destroy
  has_many :owner_recipes, :class_name => "Recipe", :foreign_key => :owner_id
  has_many :other_recipes, :class_name => "Recipe", :foreign_key => :other_id
  has_one :user, :through => :recipe
  
  ATTRS = [:email, :username, :gender, :address, :ward, :district, :city_province]
  ROLES = [
    ADMIN = "admin",
    CUSTOMER = "customer",
    TUTOR = "tutor",
    MOD = "mod"
  ]

  validates :role, :inclusion => {:in => ROLES}
  validates :gender, :inclusion => {:in => %w( Male Female )}
  before_validation :default_role
  before_validation :default_gender

  ROLES.each do |role|
    # for selecting users based on given role
    scope role.pluralize.to_sym, where(:role => role)

    # for checking the given user has the given role or not
    # lay role tu #{role?}
    define_method("#{role}?") do
      self.role == role
    end   
  end

  searchable do
    text :email, :username, :gender, :address, :ward, :district, :city_province, :role
  end

  def self.mysearch params, role
    User.reindex
    User.search do
      fulltext role do
        fields(:role)
      end
      ATTRS.each do |element|
        if params[element]
          fulltext params[element] do
            fields(element)
          end
        end
      end
    end.results
  end 

  private
    def default_role
      self.role = CUSTOMER if self.role.blank?
    end

  private
    def default_gender
      self.gender = "Male" if self.gender.nil?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!
	before_filter :authorized_user?, :except => [:self_update, :self_edit, :show]

	def authorized_user?
		redirect_to(root_path) unless current_user && current_user.admin?
	end

	def self_edit 
		@user = current_user
	end

	def self_update
		@user = User.find(current_user.id)
		if(@user.update_without_password(params[:user]))
      redirect_to root_path
		else
			render "self_edit"
		end
	end

	def index
		@users = User.paginate(:page => params[:page])
	end

	def show
		@user = User.find_by_id(params[:user_id])
	end

	def new
		@user = User.new
	end

	def edit
		@user = User.find_by_id(params[:user_id])
	end

	def update
		@user = User.find_by_id(params[:user_id])
		if(@user.update_attributes(params[:user]))
			redirect_to "/users/show/#{@user.id}"
		else
			render action: "edit"
		end
	end

	def create
		@user = User.new(params[:user])
		if(@user.save)
			redirect_to "/users/show/#{@user.id}"
		else
			render action: "new"
		end
	end

	def delete
		user = User.find_by_id(params[:user_id])
		user.delete
		redirect_to '/users/index/1'
	end
end

app/views/users/edit.haml
.big-content	
	.header-link.left.active= link_to "EDOT", "/users/edit/#{@user.id}"
	.divider.left= "|"
	.header-link.left.inactive= link_to "USERS", "/users/index/1"
	.clearboth
	.form-content
		.h1= "EDIT A USER"
		.form
			= form_for :user, :url => "/users/update/#{@user.id}" do |f|
				= f.label "Username"
				= f.text_field :username, :id => "username", :placeholder => "Input username", :autocomplete => "off"
				.clearboth

				= f.label "Email"
				= f.email_field :email, :id => "email", :placeholder => "Input email"
				.clearboth

				= f.label "Address"
				= f.text_field :address, :id => "address", :placeholder => "Input address", :autocomplete => "off"
				.clearboth

				= f.label "Ward"
				= f.text_field :ward, :id => "ward", :placeholder => "Input ward", :autocomplete => "off"
				.clearboth

				= f.label "District"
				= f.text_field :district, :id => "district", :placeholder => "Input district", :autocomplete => "off"
				.clearboth

				= f.label "City/Province"
				= f.text_field :city_province, :id => "city_province", :placeholder => "Input City/Province", :autocomplete => "off"
				.clearboth

				= f.label "Role"
				= f.select :role, [['Customer','customer'],['Tutor','tutor'],['Admin','admin'],['Mod','mod']], :id => "role"
				.clearboth

				= f.submit "Submit", :id => "submit_btn", :class => "submit_btn"
				.clearboth
				.right.error
		-if @user.errors.any?
			#error_explanation
				%h2.errors= pluralize(@user.errors.count, "error") + " prohibited this user from being updated:"
				%ul.errors
					-@user.errors.full_messages.each do |msg|
						%li.errors= msg

app/views/users/index.haml
.big-content
  - if current_user.admin?
    .header-link.left.inactive= link_to "CREATE", "/users/new"
    .divider.left= "|"
  .header-link.left.active= link_to "USERS", "/users/index/1"
  .clearboth
  - @users.each do |user|
    .small-content.left
      .text-content.left
        .h1.link= link_to "#{user.username.upcase}", "/users/show/#{user.id}"
        .h2= user.email
        .h2= user.role.capitalize
  .clearboth
  .paginate.right= will_paginate @users

app/views/users/new.haml
.big-content	
	.header-link.left.active= link_to "CREATE", "/users/new"
	.divider.left= "|"
	.header-link.left.inactive= link_to "USERS", "/users/index/1"
	.clearboth
	.form-content
		.h1= "CREATE A USER"
		.form
			= form_for :user, :url => "/users/create" do |f|
				= f.label "Username"
				= f.text_field :username, :id => "username", :placeholder => "Input username", :autocomplete => "off"
				.clearboth

				= f.label "Password"
				= f.password_field :password, :id => "password", :placeholder => "Input password", :autocomplete => "off"
				.clearboth

				= f.label "Re-enter password"
				= f.password_field :password_confirmation, :id => "password_confirmation", :placeholder => "Input password confirmation"
				.clearboth

				= f.label "Email"
				= f.email_field :email, :id => "email", :placeholder => "Input email"
				.clearboth

				= f.label "Address"
				= f.text_field :address, :id => "address", :placeholder => "Input address", :autocomplete => "off"
				.clearboth

				= f.label "Ward"
				= f.text_field :ward, :id => "ward", :placeholder => "Input ward", :autocomplete => "off"
				.clearboth

				= f.label "District"
				= f.text_field :district, :id => "district", :placeholder => "Input district", :autocomplete => "off"
				.clearboth

				= f.label "City/Province"
				= f.text_field :city_province, :id => "city_province", :placeholder => "Input City/Province", :autocomplete => "off"
				.clearboth

				= f.label "Role"
				= f.select :role, [['Customer','customer'],['Tutor','tutor'],['Admin','admin'],['Mod','mod']], :id => "role"
				.clearboth

				= f.submit "Submit", :id => "submit_btn", :class => "submit_btn"
				.clearboth
				.right.error
		-if @user.errors.any?
			#error_explanation
				%h2.errors= pluralize(@user.errors.count, "error") + " prohibited this user from being saved:"
				%ul.errors
					-@user.errors.full_messages.each do |msg|
						%li.errors= msg

app/views/users/self_edit.haml
.big-content
  .title= "EDIT YOUR PROFILE"
  .devise-content
    = form_for(:user, :url => "/users/self_update") do |f|
      %div
        = f.label :email
        = f.email_field :email
      .clearboth
      - (User::ATTRS - [:gender, :email]).each do |attribute|
        %div
          = f.label attribute
          = f.text_field attribute
        .clearboth
      = f.label :gender, "Gender", :class => "gender-label"
      = f.select :gender, options_for_select([['Male', 'Male'], ['Female', 'Female']], @user.gender), :class => "select-role"
      .clearboth
      %div= f.submit "Update", :class => "submit"
      .clearboth
    .links-block
      %span= link_to "Change your password", edit_registration_path(current_user)
    -if @user.errors.any?
      #error_explanation
        %h2.errors= pluralize(@user.errors.count, "error") + " prohibited this user from being updated:"
        %ul.errors
          -@user.errors.full_messages.each do |msg|
            %li.errors= msg

app/views/users/show.haml
.big-content
	- if current_user.admin?
		.header-link.left.inactive= link_to "CREATE", "/users/new"
		.divider.left= "|"
		.header-link.left.inactive= link_to "USERS", "/users/index/1"
		.divider.left= "|"
		.header-link.left.active= link_to "#{@user.username.truncate(20).upcase}", "/users/show/#{@user.id}"
		.clearboth
	.content
		.h3= @user.username.upcase
		- (User::ATTRS - [:username]).each do |attribute| 
			.h2
				%b= attribute.to_s.gsub("_", "/").capitalize + ": "
				= @user.send(attribute).nil? ? "Unfilled" : @user.send(attribute)
		- if current_user.admin?
			.h2.link.right= link_to "Edit this user", "/users/edit/#{@user.id}"
			.clearboth
			.h2.link.right= link_to "Delete this user", "/users/delete/#{@user.id}", :method => "post"